/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GridBehavior, GridColumn } from "smart-webcomponents/source/typescript/smart.elements";
export namespace Components {
    interface MyComponent {
        "appearance": any;
        "behavior": GridBehavior;
        "columns": GridColumn[];
        "dataSource": any;
        "editing": any;
        "pager": any;
        "paging": any;
        "selection": any;
        "sorting": any;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "appearance"?: any;
        "behavior"?: GridBehavior;
        "columns"?: GridColumn[];
        "dataSource"?: any;
        "editing"?: any;
        "pager"?: any;
        "paging"?: any;
        "selection"?: any;
        "sorting"?: any;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
